# Generated by Django 6.0.6 on 2026-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadiaria',
            name='comida_excedida',
            field=models.BooleanField(default=False, verbose_name='Comida excedida'),
        ),
        migrations.AddField(
            model_name='asistenciadiaria',
            name='horas_extra_minutos',
            field=models.IntegerField(default=0, verbose_name='Horas extra (minutos)'),
        ),
    ]
