# Generated by Django 6.0.6 on 2026-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_asistenciadiaria_comida_excedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadiaria',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='estatus',
            field=models.CharField(choices=[('completo', 'Completo'), ('pendiente', 'Pendiente'), ('ausente', 'Ausente'), ('descanso', 'Descanso'), ('justificado', 'Justificado')], default='pendiente', max_length=20, verbose_name='Estatus'),
        ),
    ]
