# Generated by Django 6.0.6 on 2026-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistenciadiaria_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='ubicacion_direccion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección'),
        ),
    ]
