# Generated by Django 6.0.6 on 2026-06-23 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_cargo_remove_empleado_puesto_empleado_apellidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_nueva', 'Nueva solicitud'), ('solicitud_aprobada', 'Solicitud aprobada'), ('solicitud_rechazada', 'Solicitud rechazada'), ('aviso', 'Aviso general')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, default='', max_length=300, verbose_name='URL')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='employees.empleado', verbose_name='Empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('maternidad', 'Maternidad'), ('paternidad', 'Paternidad'), ('permiso_cgoce', 'Permiso con goce de sueldo'), ('permiso_sgoce', 'Permiso sin goce de sueldo'), ('salida_temprana', 'Salida temprana'), ('entrada_tarde', 'Entrada tarde')], max_length=20, verbose_name='Tipo de solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, help_text='PDF o JPG (máx 5MB)', null=True, upload_to='solicitudes/', verbose_name='Documento')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estatus')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('comentario_admin', models.TextField(blank=True, default='', verbose_name='Comentario del admin')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='employees.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estatus'], name='solicitudes_estatus_b05f23_idx'), models.Index(fields=['empleado', 'estatus'], name='solicitudes_emplead_f24843_idx')],
            },
        ),
    ]
