# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.CharField(help_text='Código del empleado ej: AER015', max_length=20, unique=True, verbose_name='ID original')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('puesto', models.CharField(blank=True, default='', max_length=100, verbose_name='Puesto')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('renuncia', 'Renuncia')], default='activo', max_length=20, verbose_name='Estatus')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_renuncia', models.DateField(blank=True, null=True, verbose_name='Fecha de renuncia')),
                ('fecha_recontratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de recontratación')),
                ('id_en_dispositivo', models.CharField(blank=True, default='', help_text='ID del empleado dentro del dispositivo ZKTeco', max_length=50, verbose_name='ID en scanner')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/', verbose_name='Foto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.departamento', verbose_name='Departamento')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estatus'], name='empleados_estatus_a40136_idx'), models.Index(fields=['departamento'], name='empleados_departa_95a8c1_idx')],
            },
        ),
    ]
