# Generated by Django 6.0.6 on 2026-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_cargo_remove_empleado_puesto_empleado_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='pendiente_push',
            field=models.BooleanField(default=False, help_text='Si está activo, el dato se enviará al escáner en la próxima solicitud getrequest', verbose_name='Pendiente de push al escáner'),
        ),
    ]
