# Generated by Django 6.0.6 on 2026-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionAPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('archivo', models.FileField(help_text='Subir archivo .apk', upload_to='apk/', verbose_name='Archivo APK')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas de la versión')),
                ('activa', models.BooleanField(default=True, help_text='Solo la versión activa se ofrece para descarga', verbose_name='Activa')),
                ('peso_mb', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Peso (MB)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Versión APK',
                'verbose_name_plural': 'Versiones APK',
                'db_table': 'versiones_apk',
                'ordering': ['-creado_en'],
            },
        ),
    ]
