# Generated by Django 6.0.6 on 2026-06-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del descanso')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('tipo_calculo', models.CharField(choices=[('fijo', 'Fijo (hora exacta)'), ('flexible', 'Flexible (ventana de tiempo)')], default='flexible', max_length=20, verbose_name='Tipo de cálculo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'db_table': 'descansos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del turno')),
                ('entrada_inicio', models.TimeField(verbose_name='Inicio ventana de entrada')),
                ('entrada_fin', models.TimeField(verbose_name='Fin ventana de entrada')),
                ('prorroga_minutos', models.PositiveIntegerField(default=10, help_text='Minutos de tolerancia después del inicio de la ventana', verbose_name='Prórroga (minutos)')),
                ('tolerancia_ausencia_minutos', models.PositiveIntegerField(default=60, help_text='Si no marca en este tiempo después del inicio, se considera ausente', verbose_name='Tolerancia para ausencia (minutos)')),
                ('jornada_hrs', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas de jornada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='descanso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='horarios.descanso', verbose_name='Descanso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='horarios.turno', verbose_name='Turno'),
        ),
    ]
