# Generated by Django 6.0.6 on 2026-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_descanso_turno_horario_descanso_horario_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='clasificacion_secuencial',
            field=models.BooleanField(default=False, help_text='Si está activo, clasifica punches en orden: 1=entrada, 2=comida_inicio, 3=comida_fin, 4=salida, 5+=extra', verbose_name='Clasificación secuencial'),
        ),
        migrations.AddField(
            model_name='horario',
            name='comida_limite_hora',
            field=models.TimeField(default='15:30', help_text='Si regresa después de esta hora, se marca como comida excedida', verbose_name='Límite de regreso de comida'),
        ),
    ]
