# Generated by Django 6.0.6 on 2026-07-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_ajustar_ventana_universal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='comida_limite_hora',
        ),
    ]
