# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable', to='empleados.empleado', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='organizacion.area', verbose_name='Area'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'area')},
        ),
    ]
