# Generated by Django 6.0.6 on 2026-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('salida', models.TimeField(blank=True, null=True, verbose_name='Salida')),
                ('comida_inicio', models.TimeField(blank=True, null=True, verbose_name='Comida inicio')),
                ('comida_fin', models.TimeField(blank=True, null=True, verbose_name='Comida fin')),
                ('horas_jornada', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas jornada')),
                ('minutos_retardo', models.IntegerField(default=0, verbose_name='Minutos de retardo')),
                ('minutos_extra', models.IntegerField(default=0, verbose_name='Minutos extra')),
                ('minutos_comida', models.IntegerField(default=0, verbose_name='Minutos de comida')),
                ('incidencia_codigo', models.CharField(blank=True, default='', max_length=20, verbose_name='Código de incidencia')),
                ('estatus', models.CharField(choices=[('completo', 'Completo'), ('pendiente', 'Pendiente'), ('ausente', 'Ausente'), ('descanso', 'Descanso')], default='pendiente', max_length=20, verbose_name='Estatus')),
                ('calculado_en', models.DateTimeField(auto_now=True, verbose_name='Calculado en')),
            ],
            options={
                'verbose_name': 'Asistencia diaria',
                'verbose_name_plural': 'Asistencias diarias',
                'db_table': 'asistencias_diarias',
            },
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado_en', models.DateTimeField(verbose_name='Marcado en')),
                ('tipo', models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('comida_inicio', 'Comida inicio'), ('comida_fin', 'Comida fin'), ('extra_inicio', 'Extra inicio'), ('extra_fin', 'Extra fin')], default='', max_length=20, verbose_name='Tipo')),
                ('fuente', models.CharField(choices=[('scanner', 'Scanner ZKTeco'), ('web', 'Check-in Web'), ('manual', 'Manual')], default='scanner', max_length=20, verbose_name='Fuente')),
                ('dispositivo_serial', models.CharField(blank=True, default='', max_length=50, verbose_name='Serial del dispositivo')),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('datos_originales', models.TextField(blank=True, default='', verbose_name='Datos originales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'db_table': 'marcaciones',
                'ordering': ['-marcado_en'],
            },
        ),
    ]
