# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadiaria',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='employees.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='asistenciadiaria',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.horario', verbose_name='Horario aplicado'),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='employees.empleado', verbose_name='Empleado'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['empleado', 'fecha'], name='asistencias_emplead_d0c7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiaria',
            index=models.Index(fields=['fecha', 'estatus'], name='asistencias_fecha_f3fc23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciadiaria',
            unique_together={('empleado', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['empleado', 'marcado_en'], name='marcaciones_emplead_1560fe_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['marcado_en'], name='marcaciones_marcado_3fda82_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['fuente'], name='marcaciones_fuente_6f3110_idx'),
        ),
        migrations.AddConstraint(
            model_name='marcacion',
            constraint=models.UniqueConstraint(fields=('empleado', 'marcado_en'), name='unq_marcacion_empleado_fecha'),
        ),
    ]
