# Generated by Django 6.0.6 on 2026-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID de sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('tipo_dispositivo', models.CharField(blank=True, default='', help_text='movil o pc', max_length=10, verbose_name='Tipo de dispositivo')),
                ('navegador', models.CharField(blank=True, default='', max_length=50, verbose_name='Navegador')),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('conectado_desde', models.DateTimeField(auto_now_add=True, verbose_name='Conectado desde')),
                ('ultimo_ping', models.DateTimeField(auto_now=True, verbose_name='Último ping')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Conexión web',
                'verbose_name_plural': 'Conexiones web',
                'db_table': 'conexiones_web',
                'ordering': ['-ultimo_ping'],
            },
        ),
    ]
