# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexionweb',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AddIndex(
            model_name='conexionweb',
            index=models.Index(fields=['activa'], name='conexiones__activa_044fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='conexionweb',
            index=models.Index(fields=['empleado', 'activa'], name='conexiones__emplead_a3d65e_idx'),
        ),
    ]
