# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('diario', 'Reporte diario'), ('mensual', 'Reporte mensual'), ('retardos', 'Reporte de retardos'), ('incidencias', 'Reporte de incidencias'), ('personalizado', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('formato', models.CharField(choices=[('xlsx', 'Excel (XLSX)'), ('pdf', 'PDF'), ('csv', 'CSV')], default='xlsx', max_length=10, verbose_name='Formato')),
                ('mostrar_columnas', models.JSONField(blank=True, default=list, help_text='Lista de nombres de columna a incluir', verbose_name='Columnas a mostrar')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Plantilla de reporte',
                'verbose_name_plural': 'Plantillas de reporte',
                'db_table': 'plantillas_reporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to='reportes/', verbose_name='Archivo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('descargado', models.BooleanField(default=False, verbose_name='Descargado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reports.plantillareporte', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'db_table': 'reportes_generados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
