# Generated by Django 6.0.6 on 2026-06-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(default='', max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='', max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='empleado', max_length=20, verbose_name='Tipo de empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_verificacion_scanner',
            field=models.CharField(choices=[('huella', 'Huella'), ('facial', 'Facial'), ('ambos', 'Huella y Facial')], default='facial', help_text='Huella, facial o ambos', max_length=20, verbose_name='Tipo verificación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.cargo', verbose_name='Cargo'),
        ),
    ]
