# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del horario')),
                ('ventana_entrada_inicio', models.TimeField(verbose_name='Inicio ventana de entrada')),
                ('ventana_entrada_fin', models.TimeField(verbose_name='Fin ventana de entrada')),
                ('prorroga_minutos', models.PositiveIntegerField(default=10, help_text='Minutos de tolerancia después del inicio de la ventana', verbose_name='Prórroga (minutos)')),
                ('tolerancia_ausencia_minutos', models.PositiveIntegerField(default=60, help_text='Si no marca en este tiempo después del inicio, se considera ausente', verbose_name='Tolerancia para ausencia (minutos)')),
                ('comida_ventana_inicio', models.TimeField(verbose_name='Inicio ventana de comida')),
                ('comida_ventana_fin', models.TimeField(verbose_name='Fin ventana de comida')),
                ('comida_duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='Duración de comida permitida (minutos)')),
                ('jornada_hrs', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas de jornada')),
                ('tipo_asignacion', models.CharField(choices=[('departamento', 'Departamento'), ('area', 'Area'), ('individual', 'Individual')], max_length=20, verbose_name='Tipo de asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, to='company.area', verbose_name='Areas')),
                ('departamentos', models.ManyToManyField(blank=True, to='company.departamento', verbose_name='Departamentos')),
                ('empleados', models.ManyToManyField(blank=True, help_text='Solo para asignación individual', to='employees.empleado', verbose_name='Empleados')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entrada_esperada', models.TimeField(blank=True, null=True, verbose_name='Entrada esperada')),
                ('salida_esperada', models.TimeField(blank=True, null=True, verbose_name='Salida esperada')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_horario', to='employees.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Excepción de horario',
                'verbose_name_plural': 'Excepciones de horario',
                'db_table': 'excepciones_horario',
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='employees.empleado', verbose_name='Empleado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='schedules.horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Asignación de horario',
                'verbose_name_plural': 'Asignaciones de horario',
                'db_table': 'asignaciones_horario',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['empleado', 'fecha_inicio'], name='asignacione_emplead_18276c_idx')],
            },
        ),
    ]
