# Generated by Django 6.0.6 on 2026-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Serial')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('puerto', models.IntegerField(default=4370, verbose_name='Puerto')),
                ('modelo', models.CharField(default='SpeedFace-V3L', max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('scanner', 'Scanner ZKTeco'), ('web', 'Navegador Web')], default='scanner', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('online', 'En línea'), ('offline', 'Fuera de línea'), ('mantenimiento', 'En mantenimiento')], default='offline', max_length=20, verbose_name='Estado')),
                ('password', models.CharField(blank=True, default='0', help_text='Password de comunicación del dispositivo', max_length=50, verbose_name='Password')),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True, verbose_name='Último ping')),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivos',
                'ordering': ['nombre'],
            },
        ),
    ]
