# Generated by Django 6.0.6 on 2026-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_attlog',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último ATTLOG recibido'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_error',
            field=models.TextField(blank=True, default='', verbose_name='Último error'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último heartbeat ADMS'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='version_firmware',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Versión firmware'),
        ),
    ]
