# Generated by Django 6.0.6 on 2026-06-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('color', models.CharField(default='#FF0000', help_text='Color en formato #RRGGBB', max_length=7, verbose_name='Color (hex)')),
                ('icono', models.CharField(blank=True, default='', help_text='Clase de icono de Bootstrap', max_length=50, verbose_name='Icono')),
                ('es_automatica', models.BooleanField(default=False, help_text='Si es detectada automáticamente por el sistema (llt, finj)', verbose_name='Es automática')),
                ('requiere_justificacion', models.BooleanField(default=True, verbose_name='Requiere justificación')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de incidencia',
                'verbose_name_plural': 'Tipos de incidencia',
                'db_table': 'tipos_incidencia',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('minutos', models.IntegerField(default=0, help_text='Duración en minutos (aplica para retardos)', verbose_name='Minutos')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('justificacion', models.TextField(blank=True, default='', verbose_name='Justificación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='employees.empleado', verbose_name='Empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='incidents.tipoincidencia', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Registro de incidencia',
                'verbose_name_plural': 'Registros de incidencias',
                'db_table': 'registros_incidencia',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='registros_i_emplead_cdff78_idx'), models.Index(fields=['justificada'], name='registros_i_justifi_d286b9_idx')],
            },
        ),
    ]
